export const ROLES = {
    ADMINISTRATOR: 'administrator',
    PROPERTY_MANAGER: 'property_manager',
    TENANT: 'tenant',
    MAINTENANCE_STAFF: 'maintenance_staff',
  };
  
  export const MODULES = {
    PROPERTIES: 'properties',
    TENANTS: 'tenants',
    LEASES: 'leases',
    MAINTENANCE_REQUESTS: 'maintenance_requests',
    FINANCIALS: 'financials',
  };
  
  export const ACTIONS = {
    VIEW: 'view',
    CREATE: 'create',
    UPDATE: 'update',
    DELETE: 'delete',
    ADDREQUEST:'addwork'
  };
  
  
  export const PERMISSIONS = {
    [ROLES.ADMINISTRATOR]: {
      [MODULES.PROPERTIES]: [ACTIONS.VIEW, ACTIONS.CREATE, ACTIONS.UPDATE, ACTIONS.DELETE],
      [MODULES.TENANTS]: [ACTIONS.VIEW, ACTIONS.CREATE, ACTIONS.UPDATE, ACTIONS.DELETE],
      [MODULES.LEASES]: [ACTIONS.VIEW, ACTIONS.CREATE, ACTIONS.UPDATE, ACTIONS.DELETE],
      [MODULES.MAINTENANCE_REQUESTS]: [ACTIONS.VIEW, ACTIONS.CREATE, ACTIONS.UPDATE, ACTIONS.DELETE],
      [MODULES.FINANCIALS]: [ACTIONS.VIEW, ACTIONS.UPDATE],
    },
    [ROLES.PROPERTY_MANAGER]: {
      [MODULES.PROPERTIES]: [ACTIONS.VIEW, ACTIONS.UPDATE],
      [MODULES.TENANTS]: [ACTIONS.VIEW, ACTIONS.CREATE, ACTIONS.UPDATE],
      [MODULES.LEASES]: [ACTIONS.VIEW, ACTIONS.CREATE, ACTIONS.UPDATE],
      [MODULES.MAINTENANCE_REQUESTS]: [ACTIONS.VIEW, ACTIONS.CREATE],
      [MODULES.FINANCIALS]: [ACTIONS.VIEW, ACTIONS?.CREATE],
    },
    [ROLES.PROPERTY_MANAGER]: {
      [MODULES.PROPERTIES]: [ACTIONS.VIEW, ACTIONS.UPDATE],
      [MODULES.TENANTS]: [ACTIONS.VIEW, ACTIONS.CREATE, ACTIONS.UPDATE],
      [MODULES.LEASES]: [ACTIONS.VIEW, ACTIONS.CREATE, ACTIONS.UPDATE],
      [MODULES.MAINTENANCE_REQUESTS]: [ACTIONS.VIEW, ACTIONS.CREATE],
      [MODULES.FINANCIALS]: [ACTIONS.VIEW, ACTIONS?.CREATE],
    },
    [ROLES.TENANT]: {
      [MODULES.PROPERTIES]: [ACTIONS.VIEW],
      [MODULES.TENANTS]: [ACTIONS.VIEW, ACTIONS.UPDATE],
      [MODULES.LEASES]: [ACTIONS.VIEW],
      [MODULES.MAINTENANCE_REQUESTS]: [ACTIONS.VIEW, ACTIONS.CREATE, ACTIONS?.ADDREQUEST],

    //   [MODULES.FINANCIALS]: [ACTIONS.VIEW],
    },
    [ROLES.MAINTENANCE_STAFF]: {
      [MODULES.TENANTS]: [ACTIONS.VIEW],
      [MODULES.LEASES]: [ACTIONS.VIEW],
      [MODULES.MAINTENANCE_REQUESTS]: [ACTIONS.VIEW, ACTIONS.UPDATE],
    //   [MODULES.FINANCIALS]: [],
    }
  };